first_project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('', views.user_login, name='user_login'),
    path('index', views.index, name='index'),
    path('logout', views.user_logout, name='logout'),
    path('newWebpage', views.newWebpage, name='newWebpage'),
    path('register', views.register, name='register'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import include, path
from first_app import views

urlpatterns = [
    path('', include('first_app.urls')),
    #path('', views.index, name='index'),
    #path('', views.user_login, name='user_login'),
    path('logout', views.user_logout, name='logout'),
    path('first_app/', include("first_app.urls")),
    path('library_app/', include("library_app.urls")),
    path('admin/', admin.site.urls),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)


    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)


    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()


    def __str__(self):
        return str(self.date)


# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    profile_pic = models.ImageField(upload_to='first_app/profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import Webpage, UserProfileInfo

class NewWebpageForm(forms.ModelForm):
    class Meta():
        model = Webpage
        fields = "__all__"

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project/first_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from first_app.forms import NewWebpageForm, UserForm, UserProfileInfoForm
from datetime import date

from django.conf import settings

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                #return HttpResponseRedirect(reverse('index'))

                print(request.path)
                #return redirect('%s?next=%s' % ('first_app/login.html', request.path))
                #return render(request, request.path, {})
                return render(request, "first_app/index.html", {})
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        print(request.path)
        #Nothing has been provided for username or password.
        return render(request, "first_app/login.html", {})


@login_required
def index(request):
    my_dict = {"insert_content":"Hello I'm from First App", "my_date":date.today()}
    return render(request, "first_app/index.html", context=my_dict)

@login_required
def newWebpage(request):
    form = NewWebpageForm()

    if request.method == "POST":
        form = NewWebpageForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("Error from New Webpage Form")

    return render(request, "first_app/webpage.html", {"form":form})

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    #return HttpResponseRedirect('')
    return render(request, "first_app/login.html", {})

@login_required
def register(request):
    registered = False
    if request.method == 'POST':
        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            # Save User Form to Database
            user = user_form.save()
            # Hash the password
            user.set_password(user.password)
            # Update with Hashed password
            user.save()
            # Now we deal with the extra info!
            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)
            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user
            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']
            # Now save model
            profile.save()
            # Registration Successful!
            registered = True
        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)
    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'first_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "base.html" %}

  {% block body_block %}
    <h1>Hello this is test page!</h1>
    <h2>{{insert_content}}</h2>

    <h3>Today is {{my_date|date:"c"}}</h3>
  {% endblock %}

first_project/templates/first_app/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>

      <div class="collapse navbar-collapse" id="navbarNav">

      </div>
    </nav>
    <div class="Container">
      <div class="jumbotron">
        <h1>Please Login</h1>

        <form method="post" action="{% url 'first_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>
      </div>

    </div>

  </body>
</html>

first_project/templates/first_app/registration.html
{% extends "base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

first_project/templates/first_app/webpage.html
<!DOCTYPE html>
{% extends "base.html" %}

  {% block body_block %}
    <h1>Enter new wenpage information:</h1>
    <form  method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Submit">
    </form>

  {% endblock %}

first_project/templates/first_app/webpage_details.html
<!DOCTYPE html>
{% extends "base.html" %}

  {% block body_block %}
    

  {% endblock %}