first_project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('', views.user_login, name='user_login'),
    path('index', views.index, name='index'),
    path('logout', views.user_logout, name='logout'),
    path('newWebpage', views.newWebpage, name='newWebpage'),
    path('register', views.register, name='register'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import include, path
from first_app import views

urlpatterns = [
    path('', include('first_app.urls')),
    #path('', views.index, name='index'),
    #path('', views.user_login, name='user_login'),
    path('logout', views.user_logout, name='logout'),
    path('first_app/', include("first_app.urls")),
    path('library_app/', include("library_app.urls")),
    path('admin/', admin.site.urls),
]

first_project/library_app/urls.py
from django.urls import path
from . import views

app_name = 'library_app'

urlpatterns = [
    path('newAuthor', views.NewAuthor, name='newAuthor'),
    path('newBook', views.NewBook, name='newBook'),
]

first_project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "first_app:index" %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "first_app:newWebpage" %}">Webpage</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "library_app:newAuthor" %}">Author</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "library_app:newBook" %}">Book</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "first_app:register" %}">Registration</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "logout" %}">Logout</a>
            </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>